// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOd69JadSdMyFIaNG_-PllokQhWmSG5jU',
    appId: '1:289443051315:web:7c7fc507d2923f5bc83046',
    messagingSenderId: '289443051315',
    projectId: 'zshop-amme',
    authDomain: 'zshop-amme.firebaseapp.com',
    storageBucket: 'zshop-amme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9NKQGXHdd6p2c1X6MuBLvTqyLYugTDw4',
    appId: '1:289443051315:android:1f2eb8a3590b3de8c83046',
    messagingSenderId: '289443051315',
    projectId: 'zshop-amme',
    storageBucket: 'zshop-amme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-3JVS1x6n2jsEs9NH8QozOqFCTUXFNKo',
    appId: '1:289443051315:ios:f972c233db883045c83046',
    messagingSenderId: '289443051315',
    projectId: 'zshop-amme',
    storageBucket: 'zshop-amme.firebasestorage.app',
    iosBundleId: 'com.amme.zshop.zshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-3JVS1x6n2jsEs9NH8QozOqFCTUXFNKo',
    appId: '1:289443051315:ios:f972c233db883045c83046',
    messagingSenderId: '289443051315',
    projectId: 'zshop-amme',
    storageBucket: 'zshop-amme.firebasestorage.app',
    iosBundleId: 'com.amme.zshop.zshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOd69JadSdMyFIaNG_-PllokQhWmSG5jU',
    appId: '1:289443051315:web:49c7ee067ae25b82c83046',
    messagingSenderId: '289443051315',
    projectId: 'zshop-amme',
    authDomain: 'zshop-amme.firebaseapp.com',
    storageBucket: 'zshop-amme.firebasestorage.app',
  );
}
